const cards = [
    {card: '2', name: 'S2'},
    {card: '3', name: 'S3'},
    {card: '4', name: 'S4'},
    {card: '5', name: 'S5'},
    {card: '6', name: 'S6'},
    {card: '7', name: 'S7'},
    {card: '8', name: 'S8'},
    {card: '9', name: 'S9'},
    {card: '10', name: 'S10'},
    {card: 'J', name: 'JS'},
    {card: 'Q', name: 'QS'},
    {card: 'K', name: 'KS'},
    {card: 'A', name: 'AS'},
    {card: '2', name: 'C2'},
    {card: '3', name: 'C3'},
    {card: '4', name: 'C4'},
    {card: '5', name: 'C5'},
    {card: '6', name: 'C6'},
    {card: '7', name: 'C7'},
    {card: '8', name: 'C8'},
    {card: '9', name: 'C9'},
    {card: '10', name: 'C10'},
    {card: 'J', name: 'JC'},
    {card: 'Q', name: 'QC'},
    {card: 'K', name: 'KC'},
    {card: 'A', name: 'AC'},
    {card: '2', name: 'D2'},
    {card: '3', name: 'D3'},
    {card: '4', name: 'D4'},
    {card: '5', name: 'D5'},
    {card: '6', name: 'D6'},
    {card: '7', name: 'D7'},
    {card: '8', name: 'D8'},
    {card: '9', name: 'D9'},
    {card: '10', name: 'D10'},
    {card: 'J', name: 'JD'},
    {card: 'Q', name: 'QD'},
    {card: 'K', name: 'KD'},
    {card: 'A', name: 'AD'},
    {card: '2', name: 'H2'},
    {card: '3', name: 'H3'},
    {card: '4', name: 'H4'},
    {card: '5', name: 'H5'},
    {card: '6', name: 'H6'},
    {card: '7', name: 'H7'},
    {card: '8', name: 'H8'},
    {card: '9', name: 'H9'},
    {card: '10', name: 'H10'},
    {card: 'J', name: 'JH'},
    {card: 'Q', name: 'QH'},
    {card: 'K', name: 'KH'},
    {card: 'A', name: 'AH'},
]

export {
    cards
}